services:
  db_pg_16:
    image: postgres:16
    environment:
      POSTGRES_DB: vkEducation_postgres
      POSTGRES_USER: vk_postgres
      POSTGRES_PASSWORD: vk_postgres
    ports:
      - "6543:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
volumes:
  postgresql: { }

networks:
  backend: { }

