drop table if exists address cascade;
drop table if exists geo;
drop table if exists user_vk cascade;
drop table if exists album;
drop table if exists company;
drop table if exists security_user_vk;
drop table if exists audit;

create table  if not exists geo
(
    id  int PRIMARY KEY generated by default as identity,
    lat varchar,
    lng varchar
);

create table if not exists address
(
    id      int PRIMARY KEY generated by default as identity,
    street  varchar,
    suite   varchar,
    city    varchar,
    zipcode varchar,
    geo_id  int references geo (id) on delete set null
);

create table if not exists company
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar,
    catchPhrase varchar,
    bs          varchar
);

create table if not exists user_vk
(
    id         int generated by default as identity PRIMARY KEY,
    id_vk      int         not null,
    username   varchar(30) not null,
    email      varchar(30) unique,
    phone      varchar,
    website    varchar,
    address_id int         references address (id) on delete set null,
    company_id int         references company (id) on delete set null
);

create table if not exists album
(
    id         int generated by default as identity PRIMARY KEY,
    id_vk      int not null,
    title      varchar,
    my_user_id int references user_vk (id) on delete set null
);

create table if not exists post
(
    id         int generated by default as identity PRIMARY KEY,
    id_vk      int not null,
    title      varchar,
    body       varchar,
    my_user_id int references user_vk (id) on delete set null
);


create table if not exists security_user_vk
(
    id       int primary key generated by default as identity,
    username varchar(30),
    password varchar,
    role     varchar
);


create table if not exists audit
(
    id         int generated by default as identity primary key,
    user_vk_id int references user_vk (id),
    method     varchar,
    date       timestamp,
    params     varchar
);
