create table geo
(
    id  int PRIMARY KEY generated by default as identity,
    lat varchar,
    lng varchar
);

create table address
(
    id      int PRIMARY KEY generated by default as identity,
    street varchar,
    suite   varchar,
    city    varchar,
    zipcode varchar,
    geo_id int references geo(id) on delete set null
);

create table company(
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        name varchar,
                        catchPhrase varchar,
                        bs varchar
);

create table user_vk
(
    id       int generated by default as identity PRIMARY KEY,
    id_vk int not null,
    username varchar(30) not null,
    email    varchar(30) unique,
    phone    varchar,
    website  varchar,
    address_id int references address(id) on delete set null,
    company_id int references company(id) on delete set null
);

create table album
(
    id     int generated by default as identity PRIMARY KEY,
    id_vk int not null,
    title  varchar,
    my_user_id int references user_vk (id) on delete set null
);

create table post
(
    id     int generated by default as identity PRIMARY KEY,
    id_vk int not null,
    title  varchar,
    body   varchar,
    my_user_id int references user_vk (id) on delete set null
);


create table security_user_vk(
                                 id int primary key generated by default as identity,
                                 username varchar(30),
                                 password varchar,
                                 role varchar
);


create table audit(
                      id int generated by default as identity primary key,
                      user_vk_id int references user_vk(id),
                      method varchar,
                      date timestamp,
                      params varchar
);
